# Generated by Django 4.1.8 on 2024-07-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
